
version: "3"
services:
  postgres:
    ports:
      - ${PSQL_PORTS}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PRISMA_USERNAME}
      POSTGRES_PASSWORD: ${PRISMA_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis-data:/data
  #   ports:
  #     - ${REDIS_PORTS}
volumes:
  postgres:
  # redis-data:
